export declare const URL_PATHS: {
    CHECK_TICKET: string;
    MOBILE_LOGIN: string;
    BASE_URL_IHCM: string;
    CAS_TGT: string;
    TOKEN_IHCM: string;
    PROFILE_IHCM: string;
    UPDATE_DEVICE_INFO: string;
    SYNC_USER_IHCM: string;
    UPDATE_DEVICE_ID: string;
    LIST_ROOM_CHAT: string;
    UPDATE_STATUS_USER: string;
    LIST_USER: string;
    LIST_MESSAGE: string;
    INSERT_MESSAGE: string;
    CREATE_GROUP: string;
    REQUEST_TO_USER: string;
    CREATE_ROM_CHAT: string;
    UPLOAD_FILE: string;
    UPDATE_STATUS_VIDEO_CALL: string;
    MESSAGE: string;
    CHAT_INFO: string;
    REMOVE_GROUP: string;
    ADD_MEMBERS: string;
};
